/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMahasiswaRouteImport } from './routes/_authenticated/mahasiswa'
import { Route as AuthenticatedNilaiAkhirRouteImport } from './routes/_authenticated/nilai-akhir'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedRubrikRouteImport } from './routes/_authenticated/rubrik'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedPenilaianIndexRouteImport } from './routes/_authenticated/penilaian.index'
import { Route as AuthenticatedPenilaianRombelNpmRouteImport } from './routes/_authenticated/penilaian.$rombel.$npm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMahasiswaRoute = AuthenticatedMahasiswaRouteImport.update({
  id: '/mahasiswa',
  path: '/mahasiswa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNilaiAkhirRoute = AuthenticatedNilaiAkhirRouteImport.update({
  id: '/nilai-akhir',
  path: '/nilai-akhir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRubrikRoute = AuthenticatedRubrikRouteImport.update({
  id: '/rubrik',
  path: '/rubrik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPenilaianIndexRoute =
  AuthenticatedPenilaianIndexRouteImport.update({
    id: '/penilaian/',
    path: '/penilaian/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenilaianRombelNpmRoute =
  AuthenticatedPenilaianRombelNpmRouteImport.update({
    id: '/penilaian/$rombel/$npm',
    path: '/penilaian/$rombel/$npm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mahasiswa': typeof AuthenticatedMahasiswaRoute
  '/nilai-akhir': typeof AuthenticatedNilaiAkhirRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/rubrik': typeof AuthenticatedRubrikRoute
  '/api/$': typeof ApiSplatRoute
  '/penilaian/': typeof AuthenticatedPenilaianIndexRoute
  '/penilaian/$rombel/$npm': typeof AuthenticatedPenilaianRombelNpmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mahasiswa': typeof AuthenticatedMahasiswaRoute
  '/nilai-akhir': typeof AuthenticatedNilaiAkhirRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/rubrik': typeof AuthenticatedRubrikRoute
  '/api/$': typeof ApiSplatRoute
  '/penilaian': typeof AuthenticatedPenilaianIndexRoute
  '/penilaian/$rombel/$npm': typeof AuthenticatedPenilaianRombelNpmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mahasiswa': typeof AuthenticatedMahasiswaRoute
  '/_authenticated/nilai-akhir': typeof AuthenticatedNilaiAkhirRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/rubrik': typeof AuthenticatedRubrikRoute
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/penilaian/': typeof AuthenticatedPenilaianIndexRoute
  '/_authenticated/penilaian/$rombel/$npm': typeof AuthenticatedPenilaianRombelNpmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mahasiswa'
    | '/nilai-akhir'
    | '/pengaturan'
    | '/rubrik'
    | '/api/$'
    | '/penilaian/'
    | '/penilaian/$rombel/$npm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mahasiswa'
    | '/nilai-akhir'
    | '/pengaturan'
    | '/rubrik'
    | '/api/$'
    | '/penilaian'
    | '/penilaian/$rombel/$npm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/mahasiswa'
    | '/_authenticated/nilai-akhir'
    | '/_authenticated/pengaturan'
    | '/_authenticated/rubrik'
    | '/api/$'
    | '/_authenticated/penilaian/'
    | '/_authenticated/penilaian/$rombel/$npm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mahasiswa': {
      id: '/_authenticated/mahasiswa'
      path: '/mahasiswa'
      fullPath: '/mahasiswa'
      preLoaderRoute: typeof AuthenticatedMahasiswaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nilai-akhir': {
      id: '/_authenticated/nilai-akhir'
      path: '/nilai-akhir'
      fullPath: '/nilai-akhir'
      preLoaderRoute: typeof AuthenticatedNilaiAkhirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rubrik': {
      id: '/_authenticated/rubrik'
      path: '/rubrik'
      fullPath: '/rubrik'
      preLoaderRoute: typeof AuthenticatedRubrikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/penilaian/': {
      id: '/_authenticated/penilaian/'
      path: '/penilaian'
      fullPath: '/penilaian/'
      preLoaderRoute: typeof AuthenticatedPenilaianIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penilaian/$rombel/$npm': {
      id: '/_authenticated/penilaian/$rombel/$npm'
      path: '/penilaian/$rombel/$npm'
      fullPath: '/penilaian/$rombel/$npm'
      preLoaderRoute: typeof AuthenticatedPenilaianRombelNpmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMahasiswaRoute: typeof AuthenticatedMahasiswaRoute
  AuthenticatedNilaiAkhirRoute: typeof AuthenticatedNilaiAkhirRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedRubrikRoute: typeof AuthenticatedRubrikRoute
  AuthenticatedPenilaianIndexRoute: typeof AuthenticatedPenilaianIndexRoute
  AuthenticatedPenilaianRombelNpmRoute: typeof AuthenticatedPenilaianRombelNpmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMahasiswaRoute: AuthenticatedMahasiswaRoute,
  AuthenticatedNilaiAkhirRoute: AuthenticatedNilaiAkhirRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedRubrikRoute: AuthenticatedRubrikRoute,
  AuthenticatedPenilaianIndexRoute: AuthenticatedPenilaianIndexRoute,
  AuthenticatedPenilaianRombelNpmRoute: AuthenticatedPenilaianRombelNpmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
